### ISSUE TITLE
what happened to the "LV2Plugins" version?

### ISSUE THREAD

**Issue by ShantySuffisance** [ryukau/VSTPlugins#20]
dear ryukau thank you for all these great open source plugins! 
i wonder, why the "LV2Plugins" are gone?

**Comment by ryukau** [comment]
Hi, ShantySuffisance.

There are several reasons, but primary one is human problem related to a framework used in LV2Plugins repository. Following is a bit of time line.

My Linux environment started freezing very often. Probably the reason is a 10+ years old HDD used for Linux environment. I switched my main environment to Windows, and stopped maintaining LV2Plugins repository.

Then a person opened a issue on LV2Plugins repository. I said I won't maintain the repository anymore. Then archived the repository.

After that, that person wrote a comment on my unrelated repository. The person basically tried to push me to use a framework instead of VST 3. I thought it's creepy and inappropriate, as in stalked. I also didn't like the rhetoric used, which is to denounce VST 3 to make a framework shinier. This was a tipping point to me. I deleted LV2Plugins repository, and all the related comments to distance from the person.

If you have more questions, please open a [discussion](https://github.com/ryukau/VSTPlugins/discussions). I'm open to some conversation on this topic, but it's better to use discussions instead of issue.

---

If you are seeking source code, download link is below.

[LV2Plugins.zip](https://github.com/ryukau/VSTPlugins/files/9378039/LV2Plugins.zip)

To make it clear, I will not maintain LV2Plugins repository anymore. It's written in my hobby time, and I'm not getting paid. If you have any problem, please fork and maintain by yourself. Difference to this repository is written in `docs/dev_note/code_walkthrough.md`.

**Comment by ShantySuffisance** [comment]
thank you very much for the information and the code!
