### ISSUE TITLE
Plugins causing crashes on Fedora Linux

### ISSUE THREAD

**Issue by REIS0** [ryukau/VSTPlugins#35]
Trying some plugins on Ardour I got the following error after crashing:

```
/opt/Ardour-7.3.0/bin/ardour-7.3.0: symbol lookup error: /home/arthur/.vst3/CubicPadSynth.vst3/Contents/x86_64-linux/CubicPadSynth.so: undefined symbol: pango_font_metrics_get_height
```

Apparently this is happening with all plugins, so far all five I've tried got the same error.

But while this happens in Ardour, with Carla I got crashes with only `CubicPadSynth`, `LightPadSynth` and `Feedback Phase`. The logs from the crash were just saying basically "carla crashed" so nothing helpful.

I'm currently using Fedora Linux 37.

**Comment by ryukau** [comment]
Hi, @REIS0.

Just in case, did you build the plugins from source code? The binaries on release page of this repository are built on Ubuntu. They won't work on Fedora.

This is unlikely, but perhaps Pango is missing on your system. Try installing it if that's the case.

https://packages.fedoraproject.org/pkgs/pango/pango/

**Comment by REIS0** [comment]
Pango is not missing so I'm guessing maybe the symlink to it in Fedora is different (this happened with other libraries) so I'll try building to see how it goes.

**Comment by ryukau** [comment]
It's a bug on VST 3 SDK. The issue below has a solution to it.

https://github.com/steinbergmedia/vst3sdk/issues/103

`#include <limits>` is missing on `public.sdk/source/vst/moduleinfo/moduleinfoparser.cpp`.

**Comment by REIS0** [comment]
It worked but I got another error related to the sdk, this is getting harder than it should

```
[ 18%] Linking CXX executable ../../../../bin/Release/validator
/usr/bin/ld: CMakeFiles/validator.dir/__/__/__/source/vst/testsuite/general/scanparameters.cpp.o: in function `Steinberg::Vst::StringResult::queryInterface(char const*, void**)':
scanparameters.cpp:(.text._ZN9Steinberg3Vst12StringResult14queryInterfaceEPKcPPv[_ZN9Steinberg3Vst12StringResult14queryInterfaceEPKcPPv]+0x12): undefined reference to `Steinberg::IStringResult::iid'
/usr/bin/ld: scanparameters.cpp:(.text._ZN9Steinberg3Vst12StringResult14queryInterfaceEPKcPPv[_ZN9Steinberg3Vst12StringResult14queryInterfaceEPKcPPv]+0x4b): undefined reference to `Steinberg::IStringResult::iid'
/usr/bin/ld: ../../../../lib/Release/libbase.a(fobject.cpp.o): in function `Steinberg::Singleton::lockRegister()':
fobject.cpp:(.text+0x2a8): undefined reference to `Steinberg::Base::Thread::FLock::FLock(char const*)'
/usr/bin/ld: ../../../../lib/Release/libbase.a(fstring.cpp.o): in function `Steinberg::ConstString::copyTo(Steinberg::IStringResult*) const':
fstring.cpp:(.text+0x8598): undefined reference to `Steinberg::IString::iid'
/usr/bin/ld: ../../../../lib/Release/libbase.a(fstring.cpp.o): in function `Steinberg::StringObject::queryInterface(char const*, void**)':
fstring.cpp:(.text._ZN9Steinberg12StringObject14queryInterfaceEPKcPPv[_ZN9Steinberg12StringObject14queryInterfaceEPKcPPv]+0x7): undefined reference to `Steinberg::IStringResult::iid'
/usr/bin/ld: fstring.cpp:(.text._ZN9Steinberg12StringObject14queryInterfaceEPKcPPv[_ZN9Steinberg12StringObject14queryInterfaceEPKcPPv]+0x17): undefined reference to `Steinberg::IString::iid'
/usr/bin/ld: ../../../../lib/Release/libbase.a(fstring.cpp.o): in function `non-virtual thunk to Steinberg::StringObject::queryInterface(char const*, void**)':
fstring.cpp:(.text._ZN9Steinberg12StringObject14queryInterfaceEPKcPPv[_ZN9Steinberg12StringObject14queryInterfaceEPKcPPv]+0xdf): undefined reference to `Steinberg::IStringResult::iid'
/usr/bin/ld: fstring.cpp:(.text._ZN9Steinberg12StringObject14queryInterfaceEPKcPPv[_ZN9Steinberg12StringObject14queryInterfaceEPKcPPv]+0xef): undefined reference to `Steinberg::IString::iid'
/usr/bin/ld: ../../../../lib/Release/libbase.a(fstring.cpp.o): in function `non-virtual thunk to Steinberg::StringObject::queryInterface(char const*, void**)':
fstring.cpp:(.text._ZN9Steinberg12StringObject14queryInterfaceEPKcPPv[_ZN9Steinberg12StringObject14queryInterfaceEPKcPPv]+0x1af): undefined reference to `Steinberg::IStringResult::iid'
/usr/bin/ld: fstring.cpp:(.text._ZN9Steinberg12StringObject14queryInterfaceEPKcPPv[_ZN9Steinberg12StringObject14queryInterfaceEPKcPPv]+0x1bf): undefined reference to `Steinberg::IString::iid'
collect2: error: ld returned 1 exit status
gmake[2]: *** [public.sdk/samples/vst-hosting/validator/CMakeFiles/validator.dir/build.make:885: bin/Release/validator] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1424: public.sdk/samples/vst-hosting/validator/CMakeFiles/validator.dir/all] Error 2
gmake: *** [Makefile:91: all] Error 2
```

**Comment by ryukau** [comment]
Okay, this is the first time I see that error. This is just a guess, but try running `cmake` without `-j` as following.

```bash
cmake --build .
```

Or, disabling validator with `-DSMTG_RUN_VST_VALIDATOR=FALSE` might skip the problematic part.

```bash
cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DSMTG_MYPLUGINS_SRC_PATH="../../VSTPlugins" \
  -DSMTG_ADD_VST3_HOSTING_SAMPLES=FALSE \
  -DSMTG_ADD_VST3_PLUGINS_SAMPLES=FALSE \
  -DSMTG_RUN_VST_VALIDATOR=FALSE \ # Add this.
  ..

cmake --build .
```

If both of above doesn't solve the issue, please report the error to VST 3 SDK repository. The error indicates link failure on VST 3 validator. I don't have environment to test it for now, so can't provide a fix in this case.

While I'd like to support Linux better, I can't do it without help from people who are familiar with the specific distribution. In case of macOS, there were several people who stepped up to help me debugging the issue. Some of those lengthy conversations aren't on this repository because it was done in email.

Sorry for inconvenience.

**Comment by ryukau** [comment]
Sorry for late reply. I haven't noticed the edit. It's probably better to add a new comment when there is progress, so that I can get email notification.

Did you get core dump on crash? I'll provide debugging instruction depending on core dump is there or not.

Also, just in case, make sure to clean the previously installed plugin (Ubuntu builds) from `~/.vst3`. I'm pretty sure you did this, but I'd like to have a confirmation.

**Comment by ryukau** [comment]
In addition to above comment:

To check if core dump is produced, run following command.

```bash
coredumpctl list | tail
```

Or, maybe `-1` option is sufficient instead of `tail`.

```bash
coredumpctl list -1
```

If the bottom of the list is changing for each crash, then core dump is available.

**Comment by REIS0** [comment]
Unfortunately no changes and yes I'm cleaning the install every time.

**Comment by ryukau** [comment]
Steps to get debug information are following:

1. Edit top level `CMakeLists.txt` to reduce build time.
2. Build plugin in debug mode.
3. Attach gdb to Ardour and get backtrace.

Details are written below.

It might not work as intended, because this is the first time I use gdb this way. In this case, let me know about it. I'll work on it.

#### 1. Reduce build time
Edit [top level `CMakeLists.txt`](https://github.com/ryukau/VSTPlugins/blob/master/CMakeLists.txt) in this repository as following. `CubicPadSynth` becomes debug plugin in this case. It will be used to trigger crash in step 3.

```cmake
cmake_minimum_required(VERSION 3.20)

add_subdirectory(common)

add_subdirectory(CubicPadSynth)
```

To restore top level `CMakeLists.txt`, following command can be used.

```bash
git checkout -- CMakeLists.txt
```

#### 2. Build plugin in debug mode
Rebuild is required. Change `-DCMAKE_BUILD_TYPE=Release` to `-DCMAKE_BUILD_TYPE=Debug` as following.

```bash
cmake \
  -DCMAKE_BUILD_TYPE=Debug \ # Change here.
  -DSMTG_MYPLUGINS_SRC_PATH="../../VSTPlugins" \
  -DSMTG_ADD_VST3_HOSTING_SAMPLES=FALSE \
  -DSMTG_ADD_VST3_PLUGINS_SAMPLES=FALSE \
  -DSMTG_RUN_VST_VALIDATOR=FALSE \
  ..

cmake --build .
```

I'm not sure if it's still the case, but if cmake is generating `Makefile`, building might fail. In this case, move or delete existing `build` directory and create new one.

#### 3. Attach gdb to Ardour
Probably following command can be used to get backtrace.

```bash
gdb ardour
(gdb) r
# Ardour should be running here. Load debug plugin to trigger crash before next command.
(gdb) thread apply all bt full
```

Once backtrace is obtained, copy it to here. If it's too long, [Gist](https://gist.github.com/starred) might be used.

Above commands are paraphrase of [this answer](https://stackoverflow.com/a/54546352) found in StackOverflow.

**Comment by ryukau** [comment]
I also found that Ardour has demo version for Windows. And the plugins on this repository worked on my Windows environment. So this issue seems specific to Ardour on Linux environment.

**Comment by REIS0** [comment]
Possibly, in my case I'm using the version pre compiled from ardour website. (don't know if this can be a fedora specific issue too)

The only thing I've found that caught my eye was this:
```
[Thread 0x7fff957fa6c0 (LWP 7084) exited]
"/home/arthur/.config/UhhyouPlugins/style/style.json" is not regular file or doesn't exist.
"/home/arthur/.config/UhhyouPlugins/style/style.json" is not regular file or doesn't exist.
"/home/arthur/.config/UhhyouPlugins/style/style.json" is not regular file or doesn't exist.
```

**Comment by ryukau** [comment]
The error messages can be ignored. It is about missing optional config file.

As you pointed out, the use of pre compiled version might be the cause. Perhaps try a package provided by Fedora, and let me know if it works or not.

```bash
dnf install ardour7 # or ardour6.
```

- [ardour - Fedora Packages](https://packages.fedoraproject.org/search?query=ardour)

**Comment by REIS0** [comment]
same problem, if it work in Ubuntu I bet it's something related to fedora only, I won't be able to do much next days but I'll comment if I find something

**Comment by ryukau** [comment]
Could you download REAPER demo, and see if the plugins work on there? After extracting the archive, REAPER executable is found at `reaper_linux_x86_64/REAPER/reaper`.

Context: [This comment](https://github.com/osam-cologne/archlinux-proaudio/pull/162#issuecomment-1350388003) shows Linux environment I used last time. There's a video on the linked comment, and the plugins were working on REAPER on Fedora at that point. So I'd like to know if the situation is changed.

**Comment by REIS0** [comment]
@ryukau with Reaper is working indeed, I'll try to contact ardour devs to check what could be happening
![image](https://user-images.githubusercontent.com/38042161/232925039-1ac26bb0-f87e-40e5-a2c4-41efb51098df.png)

**Comment by REIS0** [comment]
Some updates, Paul answered (even though I asked in the wrong place) and here's what he said:
```
the problem is caused by using the wrong version of pango in either the plugin build or the ardour or both
basically someone built the plugin with a different version of pango than is used by the ardour.org ardour build
and that's illegal - plugins should be statically linked and not rely on the runtime environment to provide them with libraries they use
let me be more clear: a plugin can use whatever version of pango it wants, but it must statically link against pango
```

**Comment by ryukau** [comment]
Hmm. I think we hit a wall.

I looked into if all the required packages for VST 3 SDK contains static libraries. However, following packages are missing static library file (*.a).

- libxkbcommon
- libxkbcommon-x11
- pango

<details>
<summary>Links to Packaged Files on Debian, Ubuntu, and Fedora</summary>

Debian unstable:

- [libxkbcommon-dev/sid/amd64](https://packages.debian.org/sid/amd64/libxkbcommon-dev/filelist)
- [libxkbcommon-x11-dev/sid/amd64](https://packages.debian.org/sid/amd64/libxkbcommon-x11-dev/filelist)
- [libpango1.0-dev/sid/amd64](https://packages.debian.org/sid/amd64/libpango1.0-dev/filelist)

Ubuntu 22.04:

- [libxkbcommon-dev/kinetic/amd64](https://packages.ubuntu.com/kinetic/amd64/libxkbcommon-dev/filelist)
- [libxkbcommon-x11-dev/kinetic/amd64](https://packages.ubuntu.com/kinetic/amd64/libxkbcommon-x11-dev/filelist)
- [libpango1.0-dev/kinetic/amd64](https://packages.ubuntu.com/kinetic/amd64/libpango1.0-dev/filelist)

Fedora 38:

- [libxkbcommon-devel-1.5.0-2.fc38](https://packages.fedoraproject.org/pkgs/libxkbcommon/libxkbcommon-devel/fedora-38.html)
- [libxkbcommon-x11-devel-1.5.0-2.fc38](https://packages.fedoraproject.org/pkgs/libxkbcommon/libxkbcommon-x11-devel/fedora-38.html)
- [pango-devel-1.50.14-1.fc38](https://packages.fedoraproject.org/pkgs/pango/pango-devel/fedora-38.html)

</details>

This means that I have to build and include those libraries into this repository, but I wouldn't like to maintain static libraries which I'm not familiar with.

My understanding is that the fully statically linked program may fail if the version of statically linked library is far diverged from the system library version. For example, if some config path is changed, then the program fails because it tries to search into old path. My concern is that I have no idea how stable above libraries were in the past, so I can't determine if including static library into this repository is good idea or not.

So I won't likely work on this issue. However if someone is able to provide a solution, pull requests are welcome. A solution in this case probably requires to:

- Build and include static libraries.
- Provide `-static` option to linker.

Probably, it only requires to change the codes in `common/cmake`.

Another option might be to find a way to dynamically link Ardour dependencies, and to provide the information to Fedora packager.

I'll keep open this issue, and sorry again for inconvenience.

**Comment by ryukau** [comment]
I read somewhere that it might be possible to use the plugins, if both of Ardour and the plugins are built from source code.

**Comment by REIS0** [comment]
@ryukau I'll try this later on, unfortunately this last months some stuff appeared that need my attention so I won't be able to look at this issue for some time

**Comment by maxxatgit** [comment]
A plugin from V 0.62 cause crashes in Ubuntu 22.04/Reaper. The Accumulative Ring Mod will crash when other Uhhyou plugins are added. I started Reaper from the console, and there was the error in the console after Reaper crashed:
reaper: ../../../../src/cairo-xcb-screen.c:219: _get_screen_index: Assertion `!"reached"' failed.
Killed
I hope this helps. I think your plugins are great!

**Comment by ryukau** [comment]
@maxxatgit Thanks for the report. However it's probably not related to this issue. I opened another issue (https://github.com/ryukau/VSTPlugins/issues/54).

**Comment by ryukau** [comment]
Closing due to no response.
