### ISSUE TITLE
AMD64 Audacity Crash When Using Latticereverb

### ISSUE THREAD

**Issue by ElijahHamilton** [ryukau/VSTPlugins#36]
Audacity will load Lattice reverb, but will immediately crash when trying to open the plugin.
I am not able to record any logs from Audacity.

I am on Linux Mint(Ubuntu Based), 64bit.

**Comment by ryukau** [comment]
Hi, @ElijahHamilton.

I'd like to know the output of following command. Path to `LatticeReverb.vst3` might be different.

```bash
ldd ~/.vst3/LatticeReverb.vst3/Contents/x86_64-linux/LatticeReverb.so
```

I got above command from issue #3.

If `ldd` outputs `not found` somewhere, then it's library linking issue. In this case, you have to build plugin from source code.

Otherwise, I need backtrace for debugging. I can provide instruction in this case.

**Comment by ryukau** [comment]
Closed due to no response.
