### ISSUE TITLE
How do I use presets for Latticeverb?

### ISSUE THREAD

**Issue by embry0** [ryukau/VSTPlugins#39]
I followed the instructions from the [manual](https://ryukau.github.io/VSTPlugins/manual/LatticeReverb/LatticeReverb_en.html) to install presets for Latticeverb but they don't seem to work/get detected. Does Latticeverb support presets? Awesome plugin btw.

**Comment by ryukau** [comment]
Hi @embry0.

Some DAW may not support VST 3 presets. I got a report that they didn't work on Live 10 (not 11).

For reference, presets are working on my environment, which is:

- Windows 11
- FL Studio v21.0.3 \[build3517\]
- LatticeReverb 0.1.22

Path to the preset directory is `C:\Users\<my user name>\Documents\VST3 Presets\Uhhyou\LatticeReverb` on my environment.

**Comment by embry0** [comment]
Do they work in Live 11? I'm using LatticeReverb 0.1.22 in Live 11.3.2 on Windows 11. I think I have the directory set right as well
Reference: ![Screenshot 2023-07-05 144516](https://github.com/ryukau/VSTPlugins/assets/126282972/0382985b-b092-46f3-bc37-c55be50df71e)

Also how do I view/change the presets in LatticeReverb? There doesn't seem to be an option in the plugin

**Comment by ryukau** [comment]
I installed Live 11 demo and presets are working here. On 0:21, I clicked save button, but denied because I'm using demo version.

https://github.com/ryukau/VSTPlugins/assets/6243462/72a937c4-b28f-445e-9de2-5d27a68f33a6

Just in case below is a presets from my local directory. I forgot the details but they were probably just copied from [`presets`](https://github.com/ryukau/VSTPlugins/tree/master/presets) directory in this repository.

[Uhhyou.zip](https://github.com/ryukau/VSTPlugins/files/11957721/Uhhyou.zip)

I won't add preset management onto my plugins for now, because I personally don't use presets. It's probably faster to port identical plugin to JUCE, because I've already made GUI widget for preset saving/loading on there.

Also this part of Live 11 manual might have some hints to manage presets.

https://www.ableton.com/en/manual/managing-files-and-sets/

**Comment by embry0** [comment]
Don't know why the plugin folder doesn't get detected on my instance. Also I didn't know that you could just drag and drop presets onto the plugin itself. That's more than enough.

I understand not using presets. I just want to see what some of the presets do. Though you should consider a randomize option. It'll help newbies like me experiment with the plugin more. Thanks for the help either ways.

**Comment by ryukau** [comment]
Randomization is partially available for those blue bar region. Click to take focus, then press "r" on keyboard to randomize.
