### ISSUE TITLE
.clap format support

### ISSUE THREAD

**Issue by RustoMCSpit** [ryukau/VSTPlugins#50]
will you make these vst3 .clap as well?

**Comment by RustoMCSpit** [comment]
https://github.com/free-audio/clap

**Comment by ryukau** [comment]
It's not planned.

That said, please keep open this issue. I might port some plugins to CLAP if FL Studio adds support to it, and there's a feature that surpasses VST 3.

**Comment by RustoMCSpit** [comment]
fl studio has added CLAP support

**Comment by RustoMCSpit** [comment]
> and there's a feature that surpasses VST 3.
???

**Comment by RustoMCSpit** [comment]
> It's not planned.
> 
> That said, please keep open this issue. I might port some plugins to CLAP if FL Studio adds support to it, and there's a feature that surpasses VST 3.

sorry can yoy reword and expand all of this im not following

**Comment by ryukau** [comment]
I didn't know that FL added CLAP support. Thanks for the information.

On feature, I'm not interested in another plugin format unless it can do something VST 3 can't do.

To be clear, even if CLAP has some nice feature, I won't likely work on it any time soon.

**Comment by ryukau** [comment]
I couldn't find the news about CLAP support on FL. Since CLAP was announced, I was occasionally looking up their manual page to see if CLAP is supported. However, it's still not mentioned there.

https://www.image-line.com/fl-studio-learning/fl-studio-online-manual/html/plugins_supported.htm

Could you provide the source?

**Comment by ryukau** [comment]
I found it. It in FL Studio 2024.1 Beta 2.

- https://forum.image-line.com/viewtopic.php?p=1943400&hilit=clap#p1943400

Image-line account is required for above link.

**Comment by RustoMCSpit** [comment]
> I found it. It's in FL Studio 2024.1 Beta 2.
> 
> * https://forum.image-line.com/viewtopic.php?p=1943400&hilit=clap#p1943400
> 
> Image-line account is required for above link.

https://clapdb.tech/ another source too

**Comment by RustoMCSpit** [comment]
> I didn't know that FL added CLAP support. Thanks for the information.
> 
> On feature, I'm not interested in another plugin format unless it can do something VST 3 can't do.
> 
> To be clear, even if CLAP has some nice feature, I won't likely work on it any time soon.

clap can do many things vst3 cant do and it's open source! heres a short video https://m.youtube.com/watch?v=B2mywWyI9es

**Comment by ryukau** [comment]
Non-destructive automation seems nice. I like it.

---

This is repeating, but CLAP support is low priority for now because I'm concerning GUI more. Also please keep in mind that this is a hobby project.

In worst case, it's possible to port the plugins from this repository to my JUCE plugin repository (linked below). I made the code to be similar to this repository, in case when I somehow lost access to VST 3 SDK.

https://github.com/ryukau/UhhyouPluginsJuce

If you have time and energy, it's probably faster to do it yourself. I guess that's the spirit of Free Software.

**Comment by RustoMCSpit** [comment]
> to my JUCE plugin repository 

https://github.com/free-audio/clap-juce-extensions

**Comment by dromer** [comment]
Too bad you dropped the DPF ports, since DPF officially supports the CLAP format now.

**Comment by dromer** [comment]
> fl studio has added CLAP support

Not according to their website: https://www.image-line.com/fl-studio-learning/fl-studio-online-manual/html/plugins_supported.htm

**Comment by ryukau** [comment]
I close this issue because both participants are trolls.

---

RustoMCSpit first appeared here, demanded license change in issue #2, then opened another issue on other people's repository while pretending that RustoMCSpit is involved in this repository.

https://github.com/steinbergmedia/vst3sdk/issues/126

---

dromer first posted following comment. https://github.com/ryukau/VSTPlugins/issues/5#issuecomment-2080445344

Then posted above comment in this issue. https://github.com/ryukau/VSTPlugins/issues/50#issuecomment-2080686381

This person also posted following comment, but deleted. This one was written after the above comment in this issue. I received a notification about this comment in email.

    > fl studio has added CLAP support

    Not according to their website: https://www.image-line.com/fl-studio-learning/fl-studio-online-manual/html/plugins_supported.htm

All these comments ignores the existing comments. It indicates that the person is not interested in to help this project, but is only interested in to push DPF. I consider this behavior as harassment. This is the same reason I deleted my DPF repository in first place (See below).

https://github.com/ryukau/VSTPlugins/issues/20

I reported this user to GitHub, and got a template reply. This issue will be deleted according to the suggestion in the GitHub's reply.
