### ISSUE TITLE
L3/4Reverb Plugins don't show up in Bitwig Studio/Carla on OpenSuse Linux

### ISSUE THREAD

**Issue by ensonic** [ryukau/VSTPlugins#8]
I've downloaded these files:
```
> ll ~/Downloads/vst/L*
-rw-r--r-- 1 ensonic users 2043383 22. Jun 21:23 /home/ensonic/Downloads/vst/L3Reverb0.1.0.zip
-rw-r--r-- 1 ensonic users   37800 22. Jun 21:23 /home/ensonic/Downloads/vst/L3ReverbPresets.zip
-rw-r--r-- 1 ensonic users 2148773 22. Jun 21:23 /home/ensonic/Downloads/vst/L4Reverb0.1.1.zip
-rw-r--r-- 1 ensonic users   81276 22. Jun 21:23 /home/ensonic/Downloads/vst/L4ReverbPresets.zip
```

and installed them as documented:
```
.vst3> ll
-rwxrwxr-x 1 ensonic users 1872896 12. Jun 17:22 L3Reverb.so
-rwxrwxr-x 1 ensonic users 1872896 12. Jun 17:22 L4Reverb.so
drwxrwxr-x 4 ensonic users    4096 22. Jun 21:26 Uhhyou
```
running ldd on the plugins shows that I am not missing any libraries.

When starting bitwig I see this in the log:
```
[2020-06-22 21:39:26 indexer info] Could not read metadata for L4Reverb.so com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Not a plug-in file
[2020-06-22 21:39:26 indexer info] Could not read metadata for L3Reverb.so com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: com.bitwig.flt.library.metadata.reader.exception.CouldNotReadMetadataException: could not read metadata: Not a plug-in file
```

**Comment by ryukau** [comment]
Hi, ensonic.

VST 3 SDK only supports Ubuntu based distribution (See link below). So the zip packages on manual pages only contain binary for Ubuntu.

- https://steinbergmedia.github.io/vst3_doc/vstinterfaces/linuxSetup.html

If you are on Ubuntu based distribution, please let me know about it. I'll look into it.

If you are on Fedora or Debian, I could send binaries.

Otherwise, you have to build from source code. Build instruction is on the link below.

- [VSTPlugins/build_instruction.md at master · ryukau/VSTPlugins](https://github.com/ryukau/VSTPlugins/blob/master/build_instruction.md)

**Comment by ryukau** [comment]
Sorry, I somehow didn't read the title of this issue.

On openSUSE, this repository have to be built from source. Required package might be same as Fedora (See build instruction).

**Comment by tank-trax** [comment]
I am on Debian Buster and have to build them from source too... that being said the **ryukau/VSTPlugins** built locally, all load in Bitwig 3.2.2

**Comment by ensonic** [comment]
Ok, I'll trry that, but it is interesting, because I neither see them crash nor are there missing libraries.

**Comment by ryukau** [comment]
Closed due to no response.
